plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    // Production dependencies
    implementation 'com.google.guava:guava:31.1-jre'
    
    // JUnit 5 dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
}

application {
    mainClass = 'App'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

task hello {
    doLast {
        println 'hello this is written'
    }
}

task addition {
    doLast {
        int x = 10
        int y = 20
        println x + y
    }
}
